title: Shreya Barman
description: Early Career Management Graduate · Digital Strategy · Product & Project Management · Business Analysis

# GitHub Pages official theme + allows head customization
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Show these pages in the menu (we’ll create them next)
header_pages:
  1. index.md
  2. experience.md
  3. projects.md
  4. research.md
  5. education.md
  6. certifications.md
  7. gallery.md
  8. contact.md
