title: Shreya Barman
description: Early-Career Management Graduate · Digital Strategy · Product & Project Management · Business Analysis

# GitHub Pages official theme + allows head customization
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Show these pages in the menu (we’ll create them next)
header_pages:
  - index.md
  - experience.md
  - projects.md
  - research.md
  - education.md
  - certifications.md
  - gallery.md
  - contact.md
